### ISSUE TITLE
Version 0.60 not compatible

### ISSUE THREAD

**Issue by enri90** [duongxuannam/react-native-zoom-lightbox#1]
Only requires react-native@^0.59.8

**Comment by fukemy** [comment]
hi, can u help me know how to run this project, i run npm run ios but it's can not run

**Comment by duongxuannam** [comment]
hi @enri90. Sorry for the late reply I just got back to the origin github account. This library just updated latest react native version and control animation in UI thread by react-native-reanimated and react-native-gesture-handle. Please review if you are still interested
